### ISSUE TITLE
!important breaks the column text alignement

### ISSUE THREAD

**Issue by defhead** [Gyran/rutorrent-ratiocolor#2]
Since this #1 PR, the text right alignement is broken so it turns out very unpleasant (visually speaking...)
![Capture](https://user-images.githubusercontent.com/24367728/63932634-e1c10680-ca57-11e9-9d31-aec3a8cbd4ba.PNG)

Reverting back to `$(this).css("background-color", colorRGB(color));` fixes this issue

I would create a PR but I wouldn't wanna break "the third-party themes" compatibility.

**Comment by Gyran** [comment]
Maybe you can create a PR that contains something like they use here: https://stackoverflow.com/a/27066867 ? 

So that we only append the background color and don't replace the whole thing.

Not tested, but something like this?
```
$(this).attr('style', function(i,s) { return s + 'background-color:' + colorRGB(color) + ' !important;' });
```

**Comment by defhead** [comment]
Yep, I just tested that line of code and that fixed it.

Sorry, I can't create the PR because I already have a "fork of a fork of your repository", and the affected file has some differences in that one.

**Comment by Gyran** [comment]
Ok, that's to bad. I'm currently not using this anymore but if you ever get time to create a PR I would be happy to merge it :)

**Comment by defhead** [comment]
Actually, I just re-checked, and it will be a little bit more complicated than that.
As the style is refreshed every 3 or 4 seconds, here what happens to the DOM:
![image](https://user-images.githubusercontent.com/24367728/64082298-16111d00-cd0d-11e9-83e4-1ee640b199d8.png)
The background-color property is appended to the existing style every time, so it results in this.

**Comment by defhead** [comment]
This would work:
```javascript
$(this).attr('style', function(i, s) { return s.replace(/background-color:(.*?);/, '') + 'background-color:' + colorRGB(color) + ' !important;' });
```

What do you think?

**Comment by defhead** [comment]
We should continue this here #3
