### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by lollko** [Gyran/rutorrent-ratiocolor#4]
Hi, 

when i try ratiocolor, i just got a some error

`JS error: [***/rutorrent/plugins/rutorrent-ratiocolor/lang/en.js : 9] Uncaught TypeError: Cannot read property 'langLoaded' of undefined`

im using rtorrent 0.9.6/0.13.6 on debian 8.11 (jessie)

**Comment by Gyran** [comment]
I don't use rutorrent any longer so can't investigate exactly what happens. But it looks like from your error that the plugin haven't been properly loaded. 
How did you add the plugin?

**Comment by lollko** [comment]
just copy and paste to plugin directory

**Comment by Gyran** [comment]
What's the name of the folder of this plugin in the plugins folder?

**Comment by lollko** [comment]
folder name is "rutorrent-ratiocolor" 
as you can see in the first post

**Comment by Gyran** [comment]
try to rename the folder to `ratiocolor`

**Comment by lollko** [comment]
Nice, it works ! :) thx for your help

**Comment by Gyran** [comment]
Great, happy to help!
