### ISSUE TITLE
Cannot clone with ssh ???

### ISSUE THREAD

**Issue by solonovamax** [Gyran/rutorrent-ratiocolor#5]
I tried cloning the repo with ssh, but for some reason it gave me this:
```
[root@solo-main plugins]# git clone git@github.com:Gyran/rutorrent-ratiocolor.git ratiocolor
Cloning into 'ratiocolor'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Not sure why this happened... but it'd be nice to be able to clone with ssh, since I like doing that with all my repos.

oddly enough, `[root@solo-main plugins]# git clone https://github.com/Gyran/rutorrent-ratiocolor.git ratiocolor` *did* work. Not sure why.

**Comment by Gyran** [comment]
Do you have a public ssh key that is linked to you account on the server you try to clone from? There are no permissions on the repo that I know about that denies cloning with ssh so it seems to be an issue with authorization with Github..

**Comment by solonovamax** [comment]
Oh that's probably why lol

I have my ssh keys set up for my main account, but not my root account.

oops
